### ISSUE TITLE
Feature to Recognize Links in Tweets

### ISSUE THREAD

**Issue by chernandez7** [calanzer/Twitter-Messaging-Engine#1]
At the moment the script doesn't have any way to recognize and separate links which is one of the requirements. I would suggest using regular expressions and trying to find matches in the tweet strings for that. (Because the method of checking the first character in a word works for mentions and topics but it would be a lot harder for links. Another reason for this is because twitter shortens url's automatically and they don't start with http://)

**Comment by calanzer** [comment]
Hey thanks for recognizing those issues, my code now will recognize links I ended up using Regex to recognize links, and I store them in a separate link.
