### ISSUE TITLE
Compatibility with Python 3 and higher

### ISSUE THREAD

**Issue by chernandez7** [calanzer/Twitter-Messaging-Engine#2]
`print`is a function in Python 3+. In order to compile I had to change the syntax of the print statements to wrap the parameters with parenthesis. (Not a major issue but needed to run on Python 3 and higher versions.) 

Or maybe a mention in the readme that states what version it is compatible with would be nice.

**Comment by calanzer** [comment]
Hey yeah I totally spaced on that, I added to the read me that the code should be run in Python 3 or higher.
