### ISSUE TITLE
Suggestion for class implementation

### ISSUE THREAD

**Issue by chernandez7** [calanzer/Twitter-Messaging-Engine#3]
Another minor suggestion would be to make a **Tweet class** that holds everything that a tweet would have, effectively separating the tweet part of the script from the printing of messaging from the program. This can be done in order to make the script standalone better. (Would allow for easier refactoring and expansion in the future)

**Comment by calanzer** [comment]
Hey I just implemented a Tweet class where I pulled out my variables, list, and regex compiler. I think this helps fix the issue involved.
