### ISSUE TITLE
Implementing regular expression

### ISSUE THREAD

**Issue by the872** [calanzer/Twitter-Messaging-Engine#4]
The code was very clean and to the point but unfortunately it was not very scalable and would not test well on many cases. 

For this, I recommend that you look into [regex](https://docs.python.org/2/library/re.html) to get a better solution for parsing the tweets better. This will also help you implement a URL parser. 

With this you may need to slightly change your project's formatting but with that in mind, I can suggest a couple things:
1. Parser and testing should be separated 
2. Testing should have a greater focus on reading in test cases that better resemble tweets

**Comment by calanzer** [comment]
Hey I did end up using regex for parsing URLs and it's working great. I also separated my parser and the tests into two different classes. The code looks so much cleaner now. 
Thanks

**Comment by the872** [comment]
Looks good!

If you're looking for further improvements for the code, I would suggest making the tests more robust (maybe even design them to fail?) and sort of test things that would resemble actual tweets.
