### ISSUE TITLE
Pull out tests

### ISSUE THREAD

**Issue by skothawala** [calanzer/Twitter-Messaging-Engine#5]
Hey,

One thing I'd suggest you do is pull out testing to a different class. The testing should be separate from the actual production code that will be run. Although it's a good idea to always test before running (which is what you are doing in this case), I think there are ways to do that without keeping all your code in one class. Not only will you have a clean "main class" but also you'll be able to scale easier (tests as well as the "main class").

**Comment by spkuehl** [comment]
Saad gave me the same advice and after implementing the suggestion I agree, putting your testing class in a new file makes both the production code and the testing code easier to read.

You can do this by cutting lines 52-80 of your current commit (beafd4f) of Parser.py and pasting them in a new Test.py file. You will then also have to import the relevant objects in Parser.py you are testing to Test.py.

**Comment by calanzer** [comment]
Hey I agree with both of you and actually did pretty much exactly what you guys said. I created a new PaserTests.py file and moved over all of my tests their. Everything runs, and the code looks a lot cleaner.
Thanks
