### ISSUE TITLE
I see what you were going for

### ISSUE THREAD

**Issue by SalomonSmeke** [calanzer/Twitter-Messaging-Engine#6]
And I like it! Simple. Fast. Works. Its uncomplicated, and in its simplicity kinda foolproof.

I will say, links were a must. But most of twitters rules are weird and dumb so I like your spartan approach. 

@ are mentions
# are tags

Twitter stop being so complicated and go home.

**Comment by calanzer** [comment]
Hey Salo thanks man, and I just added Regex so that it can recognize links and add them to their very own links list.
